version: '3.8'

services:
  # AI Telecalling Application
  ai-telecalling-app:
    build: .
    container_name: ai-telecalling-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - REVERIE_API_KEY=${REVERIE_API_KEY}
      - REVERIE_APP_ID=${REVERIE_APP_ID}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - BASE_URL=${BASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./backend/public/audio:/app/backend/public/audio
      - ./backend/uploads:/app/backend/uploads
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - ai-telecalling-network

  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: ai-telecalling-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ai_telecalling
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - ai-telecalling-network

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:latest
    container_name: ai-telecalling-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - ai-telecalling-network
    profiles:
      - tools

volumes:
  mongodb_data:
    driver: local

networks:
  ai-telecalling-network:
    driver: bridge 